name: Subservices Injector
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up showcase
        run: |
          mkdir showcase
          ls -ahl
      # Inject BHNB into /showcase/bhnb/
      - name: BHNB service
        run: |
          mkdir showcase/bhnb
          git clone https://github.com/PngWnA/BHNB
          cp BHNB/src/* ./showcase/bhnb/
          ls -ahl ./showcase/bhnb
      
      # Add and commit
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: './showcase'
          author_name: PngWnA
          author_email: gnu@korea.ac.kr
          branch: master
          cwd: '.'
          default_author: github_actor
          message: 'Injecting subservice'
          pull_strategy: '--no-rebase'
          push: true